services:
  Zaeder\MultiDbBundle\Command\CreateAdminCommand:
    autoconfigure: true
    autowire: true
    arguments:
      $localEntityManagerName: '%zaeder.multidb.local.entity_manager.name%'
    tags: ['console.command']

  Zaeder\MultiDbBundle\Command\DatabaseCreateCommand:
    public: true
    autowire: true
    tags: ['console.command']
    arguments:
      $localEntityManagerName: '%zaeder.multidb.local.entity_manager.name%'
      $localConnectionName: '%zaeder.multidb.local.connection.name%'
      $distEntityManagerName: '%zaeder.multidb.dist.entity_manager.name%'
      $serverEntityClass: '%zaeder.multidb.local.server_entity.class%'

  Zaeder\MultiDbBundle\Command\DatabaseDropCommand:
    public: true
    autowire: true
    tags: ['console.command']
    arguments:
      $localEntityManagerName: '%zaeder.multidb.local.entity_manager.name%'
      $localConnectionName: '%zaeder.multidb.local.connection.name%'
      $distEntityManagerName: '%zaeder.multidb.dist.entity_manager.name%'
      $serverEntityClass: '%zaeder.multidb.local.server_entity.class%'

  Zaeder\MultiDbBundle\Command\DatabaseUpdateCommand:
    public: true
    autowire: true
    tags: ['console.command']
    arguments:
      $localEntityManagerName: '%zaeder.multidb.local.entity_manager.name%'
      $localConnectionName: '%zaeder.multidb.local.connection.name%'
      $distEntityManagerName: '%zaeder.multidb.dist.entity_manager.name%'
      $serverEntityClass: '%zaeder.multidb.local.server_entity.class%'