services:
  Zaeder\MultiDbBundle\EventSubscriber\DistDatabaseEventSubscriber:
    autoconfigure: true
    autowire: true
    arguments:
      $localEntityManagerName: '%zaeder.multidb.local.entity_manager.name%'
      $distConnectionName: '%zaeder.multidb.dist.connection.name%'
      $distEntityManagerName: '%zaeder.multidb.dist.entity_manager.name%'
      $localUserEntityClass: '%zaeder.multidb.local.user_entity.class%'

  Zaeder\MultiDbBundle\EventSubscriber\LocalUserEventSubcriber:
    autoconfigure: true
    autowire: true
    arguments:
      $localEntityManagerName: '%zaeder.multidb.local.entity_manager.name%'
      $distEntityManagerName: '%zaeder.multidb.dist.entity_manager.name%'
      $localUserEntityClass: '%zaeder.multidb.local.user_entity.class%'
      $distUserEntityClass: '%zaeder.multidb.dist.user_entity.class%'
#
#  zaeder.multidb.dist.table_prefix:
#    class: Zaeder\MultiDbBundle\EventSubscriber\TablePrefixEventSubscriber
#    arguments:
#      $prefix: '%zaeder.multidb.dist.table_prefix%'
#    tags:
#    - { name: doctrine.event_subscriber, connection: "%zaeder.multidb.dist.connection.name%" }